#!/bin/bash

OUTPUT_ROOT_DIRECTORY="/mnt/transfer/melian-audio-mobile-conversion"

if [ ! -d $OUTPUT_ROOT_DIRECTORY ]; then
	mkdir $OUTPUT_ROOT_DIRECTORY
fi

# Select each *.flac file
#for a in *.flac; do
find . -name "*.flac" -type f -print0 | while read -d $'\0' a; do
	echo "--------------------------------------------------------------------------------"

	echo "Input File: $a"

	FILE_BASE_NAME=$(basename "$a")

	echo "File Base Name: $FILE_BASE_NAME"

	# Get the tags (= metadata)
	# --no-utf8-convert
	DATE=$(metaflac "$a" --show-tag=DATE --no-utf8-convert | sed s/.*=//g)
	GENRE=$(metaflac "$a" --show-tag=GENRE --no-utf8-convert | sed s/.*=//g)
	ARTIST=$(metaflac "$a" --show-tag=ARTIST --no-utf8-convert | sed s/.*=//g)
	ALBUM=$(metaflac "$a" --show-tag=ALBUM --no-utf8-convert | sed s/.*=//g)
	TRACK_NUMBER=$(metaflac "$a" --show-tag=TRACKNUMBER --no-utf8-convert | sed s/.*=//g)
	TITLE=$(metaflac "$a" --show-tag=TITLE --no-utf8-convert | sed s/.*=//g)

	#if [ -z "$GENRE" ] || [ -z "$ARTIST" ] || [ -z "$ALBUM" ]; then
	#	echo "Incomplete tags! Skipping..."
	#
	#	continue
	#fi
	if [ -z "$GENRE" ]; then
		echo "Unknown genre! Skipping..."

		continue
	fi
	if [ -z "$ARTIST" ]; then
		#echo "Unknown artist! Skipping..."
		
		ARTIST=-

		#continue
	fi
	if [ -z "$ALBUM" ]; then
		echo "Unknown album! Skipping..."

		continue
	fi
	if [ -z "$TITLE" ]; then
		echo "Unknown title! Skipping..."

		continue
	fi

	echo "Genre: $GENRE"
	echo "Artist: $ARTIST"
	echo "Album: $ALBUM"
	echo "Track Number: $TRACK_NUMBER"
	echo "Title: $TITLE"

	GENRE_DIRECTORY=${GENRE/\//#}
	ARTIST_DIRECTORY=${ARTIST/\//#}
	ALBUM_DIRECTORY=${ALBUM/\//#}
	TITLE_FILE_PART=${TITLE/\//#}

	#echo "Genre Directory: $GENRE_DIRECTORY"
	#echo "Artist Directory: $ARTIST_DIRECTORY"
	#echo "Album Directory: $ALBUM_DIRECTORY"
	#echo "Title File Name Part: $TITLE_FILE_PART"

	# Determine output directory and file path (and give output file the correct extension)
	#OUTPUT_FILE="$OUTPUT_ROOT_DIRECTORY/$GENRE/$ARTIST/$ALBUM/${FILE_BASE_NAME[@]/%flac/mp3}"
	if [ ! -z "$TRACK_NUMBER" ]; then
		OUTPUT_FILE="$OUTPUT_ROOT_DIRECTORY/$GENRE_DIRECTORY/$ARTIST_DIRECTORY/$ALBUM_DIRECTORY/$TRACK_NUMBER. $TITLE_FILE_PART.mp3"
	else
		OUTPUT_FILE="$OUTPUT_ROOT_DIRECTORY/$GENRE_DIRECTORY/$ARTIST_DIRECTORY/$ALBUM_DIRECTORY/$TITLE_FILE_PART.mp3"
	fi
	OUTPUT_DIRECTORY=$(dirname "$OUTPUT_FILE")

	echo "Output Directory: $OUTPUT_DIRECTORY"
	echo "Output File: $OUTPUT_FILE"

	if [ -f "$OUTPUT_FILE" ]; then
		echo "Output file already exists! Skipping..."

		continue
	fi

	# Create output directory
	if [ ! -d "$OUTPUT_DIRECTORY" ]; then
		mkdir -p "$OUTPUT_DIRECTORY"
	fi

	# Convert the input file to output file in MP3 format: Stream flac into the lame MP3 encoder
	echo "Converting..."

	#-V0
	#--id3v2-utf16
	flac -d -c "$a" 2> /dev/null | lame \
		--id3v2-only --pad-id3v2 --id3v2-utf16 --ignore-tag-errors \
		--ty "$DATE" --tg "${GENRE:-12}" --ta "$ARTIST" --tl "$ALBUM" --tn "${TRACK_NUMBER:-0}" --tt "$TITLE" \
		- "$OUTPUT_FILE" 2> /dev/null

	echo "...done."

	#sleep 10
done

echo "--------------------------------------------------------------------------------"
